name: BellsForStacy
favicon: null
layout_spectrum: 0.6693918139208108
typography_spectrum: 0.11972269020043314
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7440481395460665
  lightness: 0.9625898615922779
  saturation: 0.620343473739922
  rhythmicContrast: 0.8293388686142862
purpose: []
