name: BellsForStacy
favicon: null
layout_spectrum: 0.12457
typography_spectrum: 0.11972
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ddeaf2'
    - '#5a7880'
    - '#90b2df'
    - '#e76462'
    - '#1b120b'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
