analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.12457
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.3125
  brandStrength: 0.25
  rhythmicContrast: 0.5
  brandColors:
    - '#ffffff'
    - '#19191b'
    - '#dfc19b'
    - '#535049'
    - '#cefd4e'
  lightness: 0.75
purpose: []
favicon: null
name: BellsForStacy
typography_spectrum: 0.07579
