purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7255639
  brandStrength: 0.6735589
  lightness: 0.758772
  brandColors:
    - '#8BA5C6'
    - '#DCDEDB'
    - '#121D2F'
    - '#5F3A2F'
    - '#90846D'
  rhythmicContrast: 0.1409774
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: BellsForStacy
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7468672
layout_spectrum: 0.1848371
