name: BellsForStacy
favicon: null
layout_spectrum: 0.12457
typography_spectrum: 0.07579
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#19191b'
    - '#dfc19b'
    - '#535049'
    - '#cefd4e'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
